src/Entity/Offer.php
<?php

namespace App\Entity;

use App\Entity\Trait\ContractTypesTrait;
use App\Entity\Trait\CreatedAtTrait;
use App\Entity\Trait\StatusTrait;
use App\Entity\Trait\UpdatedAtTrait;
use App\Repository\OfferRepository;
use DateTimeInterface;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: OfferRepository::class)]
//Précise que cette entité peut avoir des evenements. à l'occurence lors de la creation d'une instance (d'une nouvelle offre)
// on ajoute automatiquement avant l'enregistrement en bdd une date de création dans le trait CreatedAT ainsi qu'une date
// de modification dans le trait updatedAt
#[ORM\HasLifecycleCallbacks]
class Offer
{
    //Ici on importe les traits. Les traits sont des morceaux de codes en php qu'on peut importer dans des class qui n'ont
    // rien à voir entre elles. Ici on importes des colonnes en communs dans plusieurs entitées de l'application
    // voir les fichiers contenus dans *src/Entity/Trait/*
    use StatusTrait;
    use ContractTypesTrait;
    use CreatedAtTrait;
    use UpdatedAtTrait;

    //Déclaration d'une colonne de l'entité à l'occurence la colonne id
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['offer:read'])]
    private ?int $id = null;

    // Déclaration d'une relation MtO avec user creator. Many coté offer et one coté user car un utilisateur peut avoir
    // plusieurs offres mais une offre a uniquement un createur
    // la colonne ne peut pas etre nulle et elle fait partie du groupe offer:read, lors de la normalisation elle
    // sera donc renvoyée en front
    #[ORM\ManyToOne(inversedBy: 'offers')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['offer:read'])]
    private ?User $user_creator = null;

    #[ORM\Column(length: 255)]
    //Ici il s'agit d'une validation, un assert permet de verifier si la valeur de cette colonne dans une instance est
    // est valide, si elle ne l'ai pas l'enregistrement en bdd ne se fera pas. C'est le cas pour l'ensemble des assert.
        // Ici il s'agit d'un notBlank donc la valeur doit etre définie dans le formulaire
    #[Assert\NotBlank (message: 'Ce champ est requis')]
    #[Groups(['offer:read'])]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Groups(['offer:read'])]
    private ?string $location = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['offer:read'])]
    private ?string $salary = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\NotBlank]
    #[Groups(['offer:read'])]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank]
    #[Assert\NoSuspiciousCharacters]
    #[Groups(['offer:read'])]
    private ?string $description = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserCreator(): ?User
    {
        return $this->user_creator;
    }

    public function setUserCreator(?User $user_creator): static
    {
        $this->user_creator = $user_creator;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getSalary(): ?string
    {
        return $this->salary;
    }

    public function setSalary(?string $salary): static
    {
        $this->salary = $salary;

        return $this;
    }

    public function getDate(): DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Trait\CreatedAtTrait;
use App\Entity\Trait\StatusTrait;
use App\Entity\Trait\UpdatedAtTrait;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\Ignore;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
#[ORM\HasLifecycleCallbacks]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    use StatusTrait;
    use CreatedAtTrait;
    use UpdatedAtTrait;


    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['tool:read', 'user:read', 'thread:read', 'message:read', 'threadMessages:read'])]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\NotBlank]
    #[Assert\Email(
        message: "Cet email n'est pas valide.",
    )]
    #[Groups(['user:read', 'thread:read', 'message:read', 'threadMessages:read'])]
    private ?string $email = null;

    #[ORM\Column]
    #[Groups(['user:read', 'thread:read', 'message:read'])]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Ignore]
    #[Assert\Regex(
        pattern : "/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$/",
        message : "Le mot de passe doit contenir au moins une minuscule, une majuscule et un chiffre, et doit avoir une longueur minimale de 8 caractères."
    )]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Groups(['user:read', 'thread:read', 'message:read', 'message:read', 'threadMessages:read'])]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Groups(['user:read', 'thread:read', 'message:read', 'message:read', 'threadMessages:read'])]
    private ?string $firstname = null;

    #[ORM\Column(length: 14, nullable: true)]
    #[Assert\NotBlank]
    #[Groups(['user:read'])]
    private ?string $siret = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Groups(['user:read'])]
    private ?string $address = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank]
    #[Groups(['user:read', 'offer:read'])]
    private ?string $domain = null;

    #[ORM\Column(length: 255, nullable: true)]
/*    #[Assert\Regex(
        pattern : "/^[+](\d{3})\)?(\d{3})(\d{5,6})$|^(\d{10,10})$/",
        message : "Veuillez entrer un numéro de téléphone valide."
    )]*/
    #[Assert\NotBlank]
    #[Groups(['user:read'])]
    private ?string $phone_number = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank]
    #[Groups(['user:read', 'offer:read'])]
    private ?string $company_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['user:read', 'thread:read', 'message:read'])]
    private ?string $avatar = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['user:read'])]
    private ?string $cv = null;


    #[ORM\OneToMany(mappedBy: 'user_sender', targetEntity: Tool::class)]
    private Collection $tools;

    #[ORM\OneToMany(mappedBy: 'user_creator', targetEntity: Thread::class)]
    private Collection $threads;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: UserThread::class, orphanRemoval: true)]
    #[Groups(['user:read'])]
    private Collection $userThreads;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: UserTool::class, orphanRemoval: true)]
    #[Groups(['user:read'])]
    private Collection $userTools;

    #[ORM\OneToMany(mappedBy: 'user_creator', targetEntity: Offer::class, orphanRemoval: true)]
    #[Groups(['user:read'])]
    private Collection $offers;

    #[ORM\OneToMany(mappedBy: 'user_creator', targetEntity: Message::class)]
    #[Groups(['user:read'])]
    private Collection $messages;

    #[ORM\ManyToMany(targetEntity: Event::class, mappedBy: 'inscription')]
    #[Groups(['user:read'])]
    private Collection $events;

    #[ORM\OneToMany(mappedBy: 'user_creator', targetEntity: Information::class)]
    #[Groups(['user:read'])]
    private Collection $information;

    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    private $resetToken;

    public function __construct()
    {
        $this->tools = new ArrayCollection();
        $this->threads = new ArrayCollection();
        $this->userThreads = new ArrayCollection();
        $this->userTools = new ArrayCollection();
        $this->offers = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->events = new ArrayCollection();
        $this->information = new ArrayCollection();
    }

    public function __toString(): string
    {
        if ($this->company_name){
            return $this->company_name;
        }

        return $this->firstname . " " . $this->lastname;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getSiret(): ?string
    {
        return $this->siret;
    }

    public function setSiret(?string $siret): static
    {
        $this->siret = $siret;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getDomain(): ?string
    {
        return $this->domain;
    }

    public function setDomain(?string $domain): static
    {
        $this->domain = $domain;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?string $phone_number): static
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getCompanyName(): ?string
    {
        return $this->company_name;
    }

    public function setCompanyName(?string $company_name): static
    {
        $this->company_name = $company_name;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function getAvatarURL(): ?string
    {
        $avatar = $this->avatar;
        if ($avatar) {
            return "/uploads/avatar/" . $this->avatar;
        } else {
            return '/assets/images/placeholder_profil.png';
        }
    }

    public function setAvatar(?string $avatar): static
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getCv(): ?string
    {
        return $this->cv;

    }

    public function getCvURL(): ?string
    {
        $cv = $this->cv;
        if ($cv) {
            return "/uploads/cv/" . $this->cv;
        } else {
            return false;
        }
    }

    public function setCv(?string $cv): static
    {
        $this->cv = $cv;

        return $this;
    }


    /**
     * @return Collection<int, Tool>
     */
    public function getTools(): Collection
    {
        return $this->tools;
    }

    public function addTool(Tool $tool): static
    {
        if (!$this->tools->contains($tool)) {
            $this->tools->add($tool);
            $tool->setUserSender($this);
        }

        return $this;
    }

    public function removeTool(Tool $tool): static
    {
        if ($this->tools->removeElement($tool)) {
            // set the owning side to null (unless already changed)
            if ($tool->getUserSender() === $this) {
                $tool->setUserSender(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Thread>
     */
    public function getThreads(): Collection
    {
        return $this->threads;
    }

    public function addThread(Thread $thread): static
    {
        if (!$this->threads->contains($thread)) {
            $this->threads->add($thread);

templates/offer/_edit_offer_modal.html.twig
<div class="modal fade modal-lg" id="staticBackdrop" data-bs-backdrop="static"
     data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title" id="staticBackdropLabel">Modifier une offre</h6>
                <button type="button" class="btn-close" data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>
            {{ form_start(form) }}
            <div class="modal-body">
                <div class="d-flex justify-content-center m-2">
                    <div class="w-50 m-1">
                        {{ form_label(form.title) }}
                        {{ form_widget(form.title) }}
                        {{ form_errors(form.title) }}
                    </div>
                    <div class="w-50 m-1">
                        {{ form_label(form.location) }}
                        {{ form_widget(form.location) }}
                        {{ form_errors(form.location) }}
                    </div>
                </div>
                <div class="d-flex justify-content-center m-2">
                    <div class="w-50 m-1">
                        {{ form_label(form.contract_type) }}
                        {{ form_widget(form.contract_type) }}
                        {{ form_errors(form.contract_type) }}
                    </div>
                    <div class="w-50 m-1">
                        {{ form_label(form.salary) }}
                        {{ form_widget(form.salary) }}
                        {{ form_errors(form.salary) }}
                    </div>
                </div>
                <div class="d-flex justify-content-center m-2">
                    <div class="w-50 m-1">
                        {{ form_label(form.date) }}
                        {{ form_widget(form.date) }}
                        {{ form_errors(form.date) }}
                    </div>
                    <div class="w-50 m-1">
                    </div>
                </div>
                <div class="d-flex justify-content-center m-2">
                    <div class="w-100 m-1">
                        {{ form_label(form.description ) }}
                        {{ form_widget(form.description) }}
                        {{ form_errors(form.description) }}
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger"
                        data-bs-dismiss="modal"><em class="bx bx-x side-menu__icon me-3"></em>Fermer
                </button>
                <button type="submit" class="btn btn-primary"><em class="bx bx-edit side-menu__icon me-3"></em>Editer</button>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
</div>

templates/offer/_modal_offer_card.html.twig
<div class="modal fade" id="displayOfferModal" tabindex="-1"
     aria-labelledby="displayOfferModal" data-bs-keyboard="false"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="d-flex justify-content-end">
                <button type="button" class="btn-close m-3" data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>

            {% include "offer/_offer_card.html.twig" %}
        </div>
    </div>
</div>

templates/offer/_offer_card.html.twig
<div class="h-100 p-3 d-flex flex-column justify-content-between">
    <div>
        <p class="fs-15 fw-semibold" id="titleOffer"></p>
        <p class="text-primary fs-11"
           id="companyNameOffer"></p>
        <div class="d-flex text-gray text-primary fs-11">
            <p class="" id="contractTypeOffer"></p>
            <p class="mx-2"> • </p>
            <p class="" id="locationOffer"></p>
            <p class="mx-2"> • </p>
            <p class="" id="salaryOffer"></p>
        </div>
    </div>
    <div class="h-75 border border-black p-2">
        <p id="descriptionOffer"></p>
    </div>
    <div class="d-flex flex-column align-items-start justify-content-end mt-2 text-gray">
        <p class="fs-semibold fs-14" id="dateOffer"></p>
        <button class="btn btn-primary"><em class="bx bx-send side-menu__icon me-3"></em>Postuler</button>
    </div>
</div>

templates/offer/_offer_list_container.html.twig
<div class="border-bottom">
    <div class="d-flex w-100">
        <div class="fs-15 fw-semibold text-primary my-2">Offres d'emploi
            <hr class="col-6">
        </div>
        <div class="dropdown ms-auto">
            <button class="btn btn-sm btn-light" data-bs-toggle="dropdown">
                <span>Filtrer</span>
                <i class="fe fe-more-vertical"></i>
            </button>
            <ul class="dropdown-menu">
                <li>
                    <div class="dropdown-item">
                        <label for="location">Emplacement</label>
                        <input type="text" name="location" id="location" class="form-control">
                    </div>
                </li>
                <li>
                    <div class="dropdown-item">
                        <label for="contractType">Type de contrat</label>
                        <select name="contractType" id="contractType" class="form-control">
                            <option value=""></option>
                            {% for key,value in contractList %}
                                <option value="{{ value }}">{{ key }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </li>
                <li>
                    <div class="dropdown-item">
                        <label for="keyword">Mot clé</label>
                        <input type="text" name="keyword" id="keyword" class="form-control">
                    </div>
                </li>
                <li>
                    <div class="dropdown-item">
                        <button class="btn btn-primary" data-action="click->offer#offersFilters">
                            <em class="bx bx-filter-alt side-menu__icon me-3"></em>
                            Valider
                        </button>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="overflow-y-auto offersContainer" style="height: 70vh">
</div>
<div class="d-flex justify-content-center mt-2">
    <ul id="pagination" class="pagination-sm"></ul>
</div>

templates/offer/add_offer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Snorri | Proposer une offre{% endblock %}

{% block body %}
    {% include "layout/_title.html.twig" with {'title' : "Offres d'emploi", 'subTitle' : "Proposition d'offre"} %}
    <div {{ stimulus_controller('addOffer') }} data-addOffer-popup-value="{{ popup }}" class="d-flex justify-content-center w-100">
        {{ form_start(form) }}
        <div class="bg-white p-4 w-100 rounded">
            <div class="d-flex justify-content-center m-2">
                <div class="w-50 m-1">
                    {{ form_label(form.title) }}
                    {{ form_widget(form.title) }}
                    {{ form_errors(form.title) }}
                </div>
                <div class="w-50 m-1">
                    {{ form_label(form.location) }}
                    {{ form_widget(form.location) }}
                    {{ form_errors(form.location) }}
                </div>
            </div>
            <div class="d-flex justify-content-center m-2">
                <div class="w-50 m-1">
                    {{ form_label(form.contract_type) }}
                    {{ form_widget(form.contract_type) }}
                    {{ form_errors(form.contract_type) }}
                </div>
                <div class="w-50 m-1">
                    {{ form_label(form.salary) }}
                    {{ form_widget(form.salary) }}
                    {{ form_errors(form.salary) }}
                </div>
            </div>
            <div class="d-flex justify-content-center m-2">
                <div class="w-50 m-1">
                    {{ form_label(form.date) }}
                    {{ form_widget(form.date) }}
                    {{ form_errors(form.date) }}
                </div>
                <div class="w-50 m-1">
                </div>
            </div>
            <div class="d-flex justify-content-center m-2">
                <div class="w-100 m-1">
                    {{ form_label(form.description ) }}
                    {{ form_widget(form.description) }}
                    {{ form_errors(form.description) }}
                </div>
            </div>
            <button class="btn btn-primary" id="submitBtn">
                <em class="bx bx-send side-menu__icon me-3"></em>
                <span>Proposer une offre</span>
            </button>
        </div>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/offer/display_offers_management.html.twig
{% extends 'base.html.twig' %}

{% block title %}Snorri | Proposer une offre{% endblock %}
{% set statusList = getStaticMethod('App\\Enum\\StatusEnum', 'getTranslatedStatusList') %}
{% set contractTypeList = getStaticMethod('App\\Enum\\ContractTypeEnum', 'getTranslatedContractsList') %}
{% set statusColorList = getStaticMethod('App\\Enum\\StatusEnum', 'getTextColorStatusList') %}
{% block body %}
    {% embed "layout/_title.html.twig" with {'title' : "Offres d'emplois", 'subTitle' : "Mes offres"} %}
        {% block actions %}
            <a class="btn btn-primary" href="{{ path("app_offer_add_offer") }}"><em class="bx bx-plus side-menu__icon me-3"></em>Proposer une offre</a>
        {% endblock actions %}
    {% endembed %}
    <div class="row">
        {% for offer in offers %}
            <div class="col-xxl-3 col-xl-6 col-lg-6 col-md-6 col-sm-12">
                <div class="card custom-card" style="height:60vh">
                    <div class="card-header">
                        <div class="d-flex justify-content-between w-100">
                            <div class="card-title">{{ offer.title }}</div>
                            <div class="{{ statusColorList[offer.status] }}">{{ statusList[offer.status] }}</div>
                        </div>
                        <div class="text-gray">
                            {{ contractTypeList[offer.contractType] }}
                            •
                            {{ offer.location|default('S/O') }}
                            {% if offer.salary != null %}
                                •
                                {{ offer.salary|default('S/O') }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="card-body overflow-y-scroll h-50">
                        <p class="card-text">{{ offer.description|default('S/O') }}</p>
                    </div>
                    <div class="card-footer d-flex justify-content-between align-items-center">
                        <div>
                            <a href="{{ path('app_offer_management_show', {'id':offer.id}) }}" class="btn btn-primary"><em class="bx bx-show side-menu__icon me-3"></em>Voir</a>
                        </div>
                        <div>
                            <p class="card-text">{{ offer.date|date('d/m/Y', 'Europe/Paris') }}</p>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/offer/index.html.twig
{#
Voici le rendu twig de l'index des outils.
    Chaque vue twig extend du base.html.twig qui contient le squelette par default de la page. dans ce squelette on spécifie
    des blocks nottamment le block title et body. on rappelle ensuite ces blocks afin d'y apporter des modifier et y écrire
    du code html dedans. On ne peux pas écrire du code à l'exterieur de ces blocks
#}

{% extends 'base.html.twig' %}
{% block title %}Snorri | Offres d'emplois{% endblock %}
{% block body %}
{#
Nous utilisons la framework stimulus, il s'agit d'un framework afin de facilité l'utilisation de js dans le twig.
    On fait appelle à des controllers javascript grace au {{ stimulus_controller('offer') }}, il s'agit ici du
    *assets/controllers/offer_controller.js*
    le code js contenu dans ce controller sera donc executé dans cette vue
    On include également une layout (morceau de code) le title contenant le template pour afficher le fil d'ariane
    voir *templates/layout/_title.html.twig* on lui passe des variables tel que le titre et le sous titre
#}
    <div {{ stimulus_controller('offer') }} class="container-fluid">
        {% include "layout/_title.html.twig" with {'title' : "Offres d'emplois", 'subTitle' : "Liste des offres" }%}
        <div class="d-flex justify-content-between p-2 row">
            <div class="col-lg-3 col-md-5 col-sm-5">
                <div>
                    {#
                    En twig on découpe les page par composants. chaque composant est ensuite inclu dans la vue de
                        cette façon comme des poupées russes. voir les differents composants listés ci dessous
                    #}

                    {% include "offer/_offer_list_container.html.twig" %}
                </div>
            </div>
            <div class="col-lg-9 col-md-7 col-sm-7 bg-white rounded d-none d-sm-block p-lg-3 p-xl-5">
                <div class="h-100">
                    {% include "offer/_offer_card.html.twig" %}
                </div>
            </div>
            <div class="d-block d-sm-none">
                {% include "offer/_modal_offer_card.html.twig" %}
            </div>
        </div>
    </div>
{% endblock %}

templates/offer/show_offer_management.html.twig
{% extends 'base.html.twig' %}

{% block title %}Snorri | Proposer une offre{% endblock %}
{% set statusList = getStaticMethod('App\\Enum\\StatusEnum', 'getTranslatedStatusList') %}
{% set contractTypeList = getStaticMethod('App\\Enum\\ContractTypeEnum', 'getTranslatedContractsList') %}
{% block body %}
    {% embed "layout/_title.html.twig" with {'title' : "Offres d'emplois", 'subTitle' : "Proposition d'offre"} %}
        {% block actions %}
            <a class="btn btn-primary" href="{{ path('app_offer_management') }}"><em class="bx bx-arrow-back side-menu__icon me-3"></em>Retour</a>
        {% endblock actions %}
    {% endembed %}
    <div class="w-100 d-flex justify-content-center">
        <div class="col-lg-9 col-md-6 col-sm-7 bg-white rounded">
            <div class="h-100 p-5 d-flex flex-column justify-content-between">
                <div>
                    <div>
                        <p class="fs-15 fw-semibold" id="titleOffer">{{ offer.title }}</p>
                    </div>
                    <div>
                        <p class="text-primary fs-11"
                           id="companyNameOffer">{{ offer.userCreator.companyName|default('S/O') }}</p>
                    </div>
                    <div class="d-flex text-gray text-primary fs-11">
                        <p class="" id="contractTypeOffer">{{ offer.contractType }} </p>
                        <p class="mx-2"> • </p>
                        <p class="" id="locationOffer">{{ offer.location }}</p>
                        {% if offer.salary != "" %}
                            <p class="mx-2"> • </p>
                            <p class="" id="salaryOffer">{{ offer.salary }}</p>
                        {% endif %}

                    </div>
                </div>
                <div class="h-75 border border-black p-2">
                    <p id="descriptionOffer">{{ offer.description }}</p>
                </div>
                <div class="d-flex flex-column align-items-start justify-content-end mt-2 text-gray">
                    <p class="fs-semibold fs-14" id="dateOffer">{{ offer.date|date('d/m/Y', 'Europe/Paris') }}</p>
                    <div class="d-flex gap-2">
                        <button class="btn btn-primary" data-bs-toggle="modal"
                                data-bs-target="#staticBackdrop"><em class="bx bx-edit side-menu__icon me-3"></em>Modifier
                        </button>
                        <a href="{{ path('app_offer_management_delete', {'id':offer.id}) }}" class="btn btn-danger"><em class="bx bx-trash side-menu__icon me-3"></em>Supprimer</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{ include("offer/_edit_offer_modal.html.twig") }}
{% endblock %}